#openweathermap_error_codes.py

DATA_FROM_FUTURE_IS_UNAVAILABLE = 400000